<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find my_robot)/urdf/properties_and_inertia.xacro" />

  <xacro:macro name="laser" params="prefix">

    <link name="laser">
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.00001" />
        <xacro:cylinder_inertia mass="0.00001" r="${laser_radius}" l="${laser_height}" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${laser_radius}" length="${laser_height}"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <cylinder radius="0.05" length="0.1"/>
        </geometry>
    </collision>
    </link>

    <joint name="laser_joint" type="fixed">
      <origin xyz="${base_length/4} 0 ${base_height/2+laser_height/2}" rpy="0 0 0" />
      <parent link="${prefix}" />
      <child link="laser" />
    </joint>

    <gazebo reference="laser">
      <sensor type="ray" name="head_hokuyo_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>20</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-1.570796</min_angle>
              <max_angle>1.570796</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.10</min>
            <max>10.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
          <topicName>robot1/laser/scan</topicName>
          <frameName>laser</frameName>
        </plugin>
      </sensor>
    </gazebo>

    <gazebo reference="laser">
      <material>Gazebo/Red</material>
    </gazebo>
  </xacro:macro>

</robot>
