<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="pi" value="3.14159"/>
	<xacro:property name="scale" value="1"/>

  	<xacro:property name="base_length" value="${scale*0.5}" />
  	<xacro:property name="base_width" value="${scale*0.25}" />
  	<xacro:property name="base_height" value="${scale*0.1}" />

  	<xacro:property name="wheel_radius" value="${scale*0.1}" />
  	<xacro:property name="wheel_thickness" value="${scale*0.05}" />
  	<xacro:property name="caster_wheel_radius" value="${wheel_radius/2+0.024}" />

  	<xacro:property name="laser_mount_radius" value="${scale*0.05}" />
  	<xacro:property name="laser_mount_height" value="${scale*0.05}" />

  	<xacro:property name="laser_radius" value="${scale*0.05}" />
  	<xacro:property name="laser_height" value="${scale*0.05}" />

  	<xacro:property name="depth_camera_length" value="${scale*0.01}" />
  	<xacro:property name="depth_camera_width" value="${scale*0.1}" />
  	<xacro:property name="depth_camera_height" value="${scale*0.02}" />

  	<xacro:property name="imu_length" value="${scale*0.1}" />
  	<xacro:property name="imu_width" value="${scale*0.1}" />
  	<xacro:property name="imu_height" value="${scale*0.01}" />

	<macro name="cylinder_inertia" params="mass r l">
		<inertia  ixx="${mass*(3*r*r+l*l)/12}" ixy = "0" ixz = "0"
				iyy="${mass*(3*r*r+l*l)/12}" iyz = "0"
	            izz="${mass*(r*r)/2}" />
	</macro>

	<macro name="box_inertia" params="mass l w h">
		<inertia  ixx="${mass*(w*w+h*h)/12}" ixy = "0" ixz = "0"
	            iyy="${mass*(l*l+h*h)/12}" iyz = "0"
	            izz="${mass*(l*l+w*w)/12}" />
	</macro>

	<macro name="sphere_inertia" params="mass r">
		<inertia  ixx="${2*(mass*r*r)/5}" ixy = "0" ixz = "0"
	            iyy="${2*(mass*r*r)/5}" iyz = "0"
	            izz="${2*(mass*r*r)/5}" />
	</macro>
	
</robot>