# footprint: [[-0.25, -0.125], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
robot_radius: 0.25
# footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]

inflation_radius: 1.0
cost_scaling_factor: 3.0
transform_tolerance: 0.4
map_type: costmap

obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.5
  inflation_radius: 0.2
  track_unknown_space: false
  combination_method: 1

  observation_sources: scan
  scan: {data_type: LaserScan, topic: /robot1/scan, marking: true, clearing: true}
  # point_cloud: {data_type: PointCloud2, topic: /robot1/depth/points, marking: true, clearing: false}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.3   # max distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"